# Generated by Django 5.2.6 on 2025-10-15 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('main_image', models.FileField(upload_to='media/home/')),
                ('size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('floor', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('new', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=50)),
                ('recomended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoryhome')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
